### ISSUE TITLE
Replace batch/scrapy fetcher with a queue-based one.

### ISSUE THREAD

**Issue by philbudne** [mediacloud/story-indexer#128]
The current batch based fetcher using scrapy has several problems:

1. The current cron-based batch launcher seems to kill batches that haven't completed (see https://github.com/mediacloud/story-indexer/issues/127)
2. If the fetcher is (re)started late in the (GMT) day, many batches may not complete
3. Restarting the fetcher re-does all the fetches (generating duplicate work for the parser if we queue on-the-fly)
4. Deployment to production can only be done once a day

I believe a fetcher that keeps all URLs in a queue would solve these problems.

I wrote a demo (using asyncio) that demos this, but a shortcoming of this is that all asyncio tasks run in a single thread (can only use one CPU core), but it was easier/safer to write the demo this way.

**Comment by philbudne** [comment]
I've opened PR https://github.com/mediacloud/story-indexer/pull/236 with the following description:

Adds two new files, and some minor infrastructure changes (logging and "fast requeue") to put my crude queue-based fetcher "in tree", and available if/until needed.

The "theory of operation" is that once a story is queued, all state is maintained in the queue, and the fetcher runs continuously servicing the queue.  If there is an outage, the queue will be loaded with all unfetched articles when the system is restarted.

All fetching work is done in threads (can use regular blocking code/libraries): the "scheduler" keeps a single lock on all critical data which is only required:
1. to "issue" (start) a story
2. when the fetch attempt has completed
3. for the main thread, once a minute to do cleanup & reporting.

Stats are reported on every story handled (connection error, HTTP error, etc). If a fetch fails due to a "soft" error (DNS lookup error, connection failed, some HTTP 5xx codes) the story will be retried in an hour up to 12 times (scrapy tries once, at end of run?).

The scheduler keeps track (by fully qualified domain name) of:
1. whether a connection has failed recently, and if so, defers fetching (to avoid repeated 30s timeouts on connect attempts)
2. number of active fetches for the FQDN
3. average latency of successful fetches, and uses that to try to issue enough requests to keep a fixed number active like scrapy does (or, alternatively to limit connection interval and concurrent connections).

If the a dequeued item can't be started ("issued") immediately, it's requeued to the "fetcher-fast" queue, and will reappear (at the end a short delay) at the end of the input queue.  This puts load on RabbitMQ (when the queue contains nothing but URLs for a few larger domains), but avoids hairly/delicate bookkeeping in the fetcher (the current Worker class doesn't allow keeping a message "checked-out" (in the library sense) of the queue, and if it did, workers could only keep an unacknowledged story for 30 minutes before RabbitMQ has a fit (and closes the connection)).

Which fetcher (batch or queue) is used is controlled by deploy.sh (default in PIPELINE_TYPE is "batch-fetcher"; running deploy with `-T queue-fetcher` will deploy a regularly named indexer stack (dev/staging or prod) using the queue based fetcher instead of the batch-fetcher.

**Comment by philbudne** [comment]
Comparing runs of the batch and queue based fetchers run on the same RSS file:

Analyzing parser log messages (displays final URL) comparing:

production batch fetcher run on mc-2024-02-22.rss.gz (from 2024-02-24
00:00:02 to 2024-02-24 10:07:59)

threaded queue based fetcher with the same input
(run 2024-03-01 18:14:36 to 2024-03-01 02:14:35)

469131 stories from batch fetcher
512002 stories from queue fetcher
450054 URLs seen in both

19077 URLS from batch fetcher only
61948 URLs from queue fetcher only

Looking at URL domains:
29375 final FQDNs with same count
3398 final FQDNs with more URLs from queue fetcher
466 final FQDNs with more URLs from batch fetcher

Columns for collect.csv.txt (attached below)
FQDN rss batch comp queue

rss column is without URLs with "non-news" domains
comp is '=' if equal, '>' if batch > queue, '<' if batch < queue

**Comment by philbudne** [comment]
[collect.csv.txt](https://github.com/mediacloud/story-indexer/files/14475109/collect.csv.txt)

**Comment by kilemensi** [comment]
Much appreciated @philbudne 

Trying to understand the numbers,
>threaded queue based fetcher with the same input
(run 2024-03-01 18:14:36 to 2024-03-01 02:14:35)
>
Did this rollover to the next day i.e. ended at 2024-03-**02** 02:14:35?

>469131 stories from batch fetcher
>512002 stories from queue fetcher
>
Difference of about 50,000 is a lot. Do we know where they ended up?

**Comment by philbudne** [comment]
Counts of rows in tab separated files of rss_url, content-length, norm_url extracted from WARC files:
```
(venv) pbudne@ifill:~/tqfetch$ wc */warc.tsv
   474395   1423270 106243863 batch/warc.tsv
   514655   1544066 115016003 tq/warc.tsv
```

**Comment by philbudne** [comment]
Correction on date/time of queue fetcher run: was 2024-03-01 01:14 thru 2024-03-01 18:47, seen in the WARC file names:
```
(venv) pbudne@ifill:/var/tmp/tq$ ls | head -3
pbudne-20240301011519-1-aeabf6512652.warc.gz
pbudne-20240301011944-2-aeabf6512652.warc.gz
pbudne-20240301012409-3-aeabf6512652.warc.gz
(venv) pbudne@ifill:/var/tmp/tq$ ls | tail -3
pbudne-20240301174543-135-aeabf6512652.warc.gz
pbudne-20240301182122-136-aeabf6512652.warc.gz
pbudne-20240301184716-137-aeabf6512652.warc.gz
```

The production run WARC files:
```
(venv) pbudne@ramos:~/tqfetch$ ls /srv/data/docker/indexer/worker_data/archiver/2024/02/24 | head -3
mc-20240224000408-362-861706228fe3.warc.gz
mc-20240224000549-363-861706228fe3.warc.gz
mc-20240224000656-364-861706228fe3.warc.gz
(venv) pbudne@ramos:~/tqfetch$ ls /srv/data/docker/indexer/worker_data/archiver/2024/02/24 | tail -3
mc-20240224112245-467-861706228fe3.warc.gz
mc-20240224113745-468-861706228fe3.warc.gz
mc-20240224115245-469-861706228fe3.warc.gz
```

**Comment by philbudne** [comment]
Latest comparison run.
Both batch and queue fetchers run against empty ES (so all unique stories created, and archived) against full generated RSS file for Sunday 2024-03-24.  Original RSS link (and normalized URL and content length) extracted from generated WARC files to generate TSV files, then loaded into sqlite3.

```
(venv) pbudne@bernstein:~/tqfetch/2024-03-24$ sh queries.sh 
======== total rss file entries
select count(1) from rss;
325302
======== total batch fetch pages
select count(1) from batch;
289303
======== total queue fetch pages
select count(1) from queue;
302594
======== total common pages
select count(1) from batch where rss_url in (select rss_url from queue);
286350
======== total common pages again
select count(1) from queue where rss_url in (select rss_url from batch);
286350
======== total fetched by batch fetcher, but not queue fetcher
select count(1) from batch where rss_url not in (select rss_url from queue);
2953
======== total fetched by queue fetcher but not batch fetcher
select count(1) from queue where rss_url not in (select rss_url from batch);
16244
```

Top 20 totals of missing pages by canonical domain for queue fetcher
(NOTE! includes npr.org and wsj.com)
```
(venv) pbudne@bernstein:~/tqfetch/2024-03-24$ head -20 queue.missing 
ahewar.org	376
parseek.com	174
ouest-france.fr	104
kp.ru	92
thespun.com	82
uza.uz	81
uol.com.br	81
vnanet.vn	75
vedomosti.ru	75
vietnamplus.vn	74
kuna.net.kw	73
bbarta24.net	71
wsj.com	59
fontanka.ru	52
am	52
ndtv.com	47
npr.org	42
google.com	40
goo.ne.jp	32
tn.ai	30
```

Top 20 totals of missing pages by canonical domain for batch fetcher:
```
(venv) pbudne@bernstein:~/tqfetch/2024-03-24$ head -20 batch.missing 
iribnews.ir	645
upstract.com	548
mehrnews.com	516
tass.ru	447
isna.ir	428
india.com	368
milenio.com	154
parseek.com	151
republika.co.id	150
epokaere.com	105
berlingske.dk	103
armenpress.am	101
vz.ru	97
uol.com.br	96
elheraldodechihuahua.com.mx	93
banglanews24.com	91
ilmattino.it	87
rt.com	85
index.hu	82
folha.com.br	81
```

Number of domains with missing pages for each:
```
(venv) pbudne@bernstein:~/tqfetch/2024-03-24$ wc -l *missing
 1613 batch.missing
  333 queue.missing
```

**Comment by philbudne** [comment]
Now in production.

Additional fetcher statuses that can show in grafana:
"noconn" -- connection attempt failed
"skipped" -- a connection attempt  to the site failed within the last "conn retry" minutes (default: 10)
"busy" -- after a delay, it turned out there were already the maximum number of concurrent requests active for the site
"skipped2" -- after a delay, a connection attempt  to the site failed within the last "conn retry" minutes
"not-text" -- the returned document was not text (likely: audio, still photo, video, pdf)
"no-url" -- RSS entry had no URL (unlikely)
"badurl1" -- RSS entry URL parse failed
"non-news2" -- redirect to a "non-news" domain
"badredir" -- empty redirect URL
"badredir2" -- redirect URL parse failed [I THINK THIS SHOULD BE badurl2?!!]
"no-html" -- zero length response
"no-host" -- URL had no host part!

In addition to all the previous HTTP and URL check statuses.
