### ISSUE TITLE
elasticsearch snapshot deployment/configuration issues/questions

### ISSUE THREAD

**Issue by philbudne** [mediacloud/story-indexer#153]
I did a development deployment from main branch, and found the following:

1. elastic_snapshot_cronjob_enable used in docker-compose template, but not set
2. I changed this to elasticsearch_snapshot_cronjob_enable for consistancy and defaulted to "false" in deploy.sh for dev/staging
3. elastic-snapshot service starts fails and restarts
4. wrapped elastic-snapshot service definition in `{% if elasticsearch_snapshot_cronjob_enable == 'true' %}` to disable

So right now it's disabled for development and staging deploys,
and I think it will be re-run whenever a production deployment is done (typically after 00:00 GMT, right after when it runs via cronjob).

Issues/questions:
1. Would it be meaningful/useful to run/test elasticsearch snapshots  in dev deploys?
2. Ideally, it would be good to gave staging deploys run the code once (ie; with cron disabled).  If this is possible/reasonable, what additional configuration is needed?
3. Is all configuration in place to deploy elasticsearch snapshots to production?

**Comment by thepsalmist** [comment]
We created two S3 buckets (snapshot-repositories) `mediacloud-elasticsearch-snapshots` and `test-mediacloud-elasticsearch-snapshots` for production and staging/dev. 
I believe we can have three buckets for each of the stages (means adding a `staging-mediacloud-elasticsearch-snapshots` repo)

> Ideally, it would be good to gave staging deploys run the code once (ie; with cron disabled). If this is possible/reasonable, what additional configuration is needed?

Wouldn't we want to take snapshots for `staging` periodically? could be longer than the current default (daily) timeframes?
Configuration wise: would involve add a bash script on the `es-setup` service to load the S3 settings into Elasticsearch's keystore.

> Is all configuration in place to deploy elasticsearch snapshots to production?

Yes,

**Comment by philbudne** [comment]
Regarding snapshotting the staging ES DB;

Since staging only runs a single batch (of 500K articles, with no cron restart), and only to test whether it's ready for production, I think the data in ES is disposable (ie; could be erased before every run) tho right now it has data from a week-long run (with an older schema?) that could be of use testing the news-search-api.

So, I think the primary value of snapshotting staging would be to test that the code to trigger snapshots does the right thing, and that snapshots indeed appear on S3 (perhaps via a command line option to the elastic-snapshot script that logs at ERROR or CRITICAL if the snapshot fails?)

Finally (thinking out loud here): Might it make sense to:
1. have indexer.scripts.elastic-snapshot make sure the snapshot is registered
2. make sure the S3 keys are loaded?
