### ISSUE TITLE
importer: many WARNINGS on published_date "None"

### ISSUE THREAD

**Issue by philbudne** [mediacloud/story-indexer#186]
Every(?) missing published_date is logged as a warning by the importer:
`Error parsing date: 'time data 'None' does not match format '%Y-%m-%d'`

Perhaps `if publication_date_str:`  in the`index_routing` function should be `if publication_date_str and publication_date_str != 'None':`??

**Comment by philbudne** [comment]
Since we have to re-index all data, perhaps we could store unknown publication data as Python `None` / JSON `null` instead of the string `"None"`???

**Comment by pgulley** [comment]
I'll move on this asap

**Comment by philbudne** [comment]
This issue will be mooted by https://github.com/mediacloud/story-indexer/pull/211 since the code that was logging the error will have gone away.
