### ISSUE TITLE
Refactor Elastic conf to not require S3 credentials for development deployment

### ISSUE THREAD

**Issue by thepsalmist** [mediacloud/story-indexer#290]
Currently, the `elastic-conf` service throws an error when any of the args is missing, this includes ~ELASTICSEARCH_SNAPSHOT_REPO, which is an S3 repository. As mentioned by @philbudne it isn't a necessity to have S3 credentials for a dev deployment. 
To do; refactor the elastic-conf to capture the above
Question: Should we have a `dev.sh` file in private config repo to maintain any dev deployment secrets?

**Comment by kilemensi** [comment]
If we want to continue running/testing SLM in `dev`, using a [filesystem repository](https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshots-filesystem-repository.html) rather than `S3` is probably the better approach; should eliminate the need of S3 credentials in `dev`.

**Comment by philbudne** [comment]
>  Question: Should we have a dev.sh file in private config repo to maintain any dev deployment secrets?

My preference: no.  People should be able to test/develop code without access to any secrets.

**Comment by thepsalmist** [comment]
Resolved in #295
