### ISSUE TITLE
elastic-conf error, questions

### ISSUE THREAD

**Issue by philbudne** [mediacloud/story-indexer#296]
elastic-conf.py is currently erroring out and restarting in production (due to non-existent backup repository?).

I also have the following questions:
1. can/should elastic-conf create/configure the repository (pass in bucket & keys from private config)
2. since multiple flavors of production stacks can exist (csv, rss, hist) as well as normal production, should elastic-conf perform all actions in all environments (if there is a version skew between stacks, there could be "bouncing" config)?

**Comment by philbudne** [comment]
Whoops!  Just opened my email and spotted https://github.com/mediacloud/story-indexer/pull/295 (addressing the top item?)

**Comment by thepsalmist** [comment]
The immediate sentry errors arising from invalid S3 repo configuration on `story-indexer-config prod.sh` have been addressed by setting the correct repo & deployed with the latest release from main.

> indexer_elastic-conf.1.s8xefjfumbbv@ramos.angwin    | 2024-06-05 06:27:30,502 | INFO | elastic-conf | SLM policy created successfully.
indexer_elastic-conf.1.s8xefjfumbbv@ramos.angwin    | 2024-06-05 06:27:30,502 | INFO | elastic-conf | All ES configurations applied successfully.

Proposed enhancements & questions to `elastic-conf` raised in #297
