### ISSUE TITLE
Migrate ILM Backups to Back Blaze

### ISSUE THREAD

**Issue by pgulley** [mediacloud/story-indexer#309]

**Comment by pgulley** [comment]
Currently ILM are going to S3

**Comment by thepsalmist** [comment]
Elasticsearch ILM backups already in backblaze,
1. Same bucket size in S3 and B2 ~ 3.2 TB



![Image](https://github.com/user-attachments/assets/ae342fc3-4b42-4a58-91fa-882cad255b69)
![Image](https://github.com/user-attachments/assets/d5d65fb2-79e2-4ee6-a39d-0d63e5e36af5)

2. Elasticsearch data directory from Ramos,Woodward.Bradley

> 2.0T	./elasticsearch

**Comment by thepsalmist** [comment]
Last B2 ILM snapshot

` "snapshots": [
        {
            "snapshot": "snapshot-2024.08.01-nozfnxqaqyim8mmev6knyq",
            "uuid": "eIt7BZVXTTeBjto24kZ2Tw",
            "repository": "mc_story_indexer",
            "version_id": 8500008,
            "version": "8500008",
            "indices": [
                "mc_search-000001",
                "mc_search-000003",
                "mc_search-000002"
            ],
            "data_streams": [],
            "include_global_state": true,
            "metadata": {
                "policy": "bi_weekly_slm"
            },
`
