### ISSUE TITLE
balanced and redundant access to elasticsearch servers

### ISSUE THREAD

**Issue by philbudne** [mediacloud/story-indexer#81]
I'm opening this issue to discuss/catalog/crystalize the issues around elasticsearch redundancy and load balancing.

My understanding is that our goal is to run three elasticsearch servers in a cluster, with all shards replicated across two servers.
This should make the loss of any single server survivable.

Having the indexer and news-search API services each point to any single elasticsearch server would be both fragile (requiring manual intervention/redeployment in the face of a server failure) and result in unfair distribution of workload.

In today's (2023-09-27) meeting I suggested using DNS "round robin" (DNSRR) for access to elasticsearch servers.

I did some investigation, and here's what I found:

DNSRR may be useless in some circumstances, due to implementation of RFC 3484 Rule 9 in getaddrinfo (the modern C library call to resolve a hostname to one or more addresses) to mean "select the address with the longest common prefix to the very last bit" making address preference ordering deterministic when the servers and the client are on the same subnet.

Some things I also learned (which only apply to servers running as Docker containers):

1. Docker swarm implements a "routing mesh" (for requests originating outside the server? via the "ingress" network??)

2. The docker-compose file has an "endpoint_mode" attribute for services:
https://docs.docker.com/compose/compose-file/compose-file-v3/#endpoint_mode
The default is "vip": docker assigns a virtual IP address for the service and tranparently routes requests to the Docker DNS name for the service.  The alternative is "dnsrr" where Docker DNS returns a list of addresses for each container.

Also:

The news-search-api  accepts multiple URLs for `eshost` configuration:
https://github.com/mediacloud/news-search-api/blob/main/api.py#L29
And passes them as a list to the `Elasticsearch` constructor:
https://elasticsearch-py.readthedocs.io/en/v8.10.0/api.html#module-elasticsearch

**Comment by philbudne** [comment]
We should test to make sure things work if we bring down an Elastic Search server that the indexer and/or elastic-stats containers are connected to before closing this!

**Comment by thepsalmist** [comment]
We are now connecting to all three Elasticsearch nodes on staging & prod, and the New Search API can also connect to the three. 
Can we close this?

**Comment by philbudne** [comment]
> Can we close this?
yes
