### ISSUE TITLE
Improve handling of parser errors

### ISSUE THREAD

**Issue by philbudne** [mediacloud/story-indexer#86]
When mcmetadata.extract throws a BadContentError the story is currently being sent to the parser quarantine queue.

I've unloaded 50 stories to angwin:~pbudne/parser-quar as binary files containing pickled Story objects for examination.

ISTR  exceptions are possible if there is too little data: just count and discard?

**Comment by philbudne** [comment]
Thought: If mcmetadata subclassed mcmetadata.exceptions.BadContentError for different, specific errors, it would eliminate the need for parser.py to examine the exception message to select a status string (it could catch ContentTooShort and select status=short)

**Comment by pgulley** [comment]
I agree that mcmetadata errors could be more distinct, I'll move on that! 
Still haven't found exactly what's causing the unicode decode errors- I'm finding that while manually decoding the stories you pulled out, the majority of them throw no errors and decode successfully! I'll follow up.

**Comment by pgulley** [comment]
BadContentError is only raised by mcmetadata in the case where content is too short- so there's not really any disambiguation to be done. Maybe we should just rename the error to ContentTooShortError or suchlike? I don't think there are any other projects which meaningfully depend on this, but it might be make work for others.

**Comment by philbudne** [comment]
If too short is the only error that could ever conceivably be thrown
there's no need to do anything, and it would be lowest impact to not
rename it (tho leaving an alias `BadContentError = ContentTooShortError`
_could_ be done).

If it's a all conceivable that the same routine could throw another
error, then I think making each case a subclass of a common class
might be the way to go.  Anyone catching BadContentError will catch
all the errors.

Right now, maybe just catch BadContentError and count it as
"bad-content"??

**Comment by pgulley** [comment]
Addressing in #129

**Comment by pgulley** [comment]
#129 was merged, so closing!
